name: Swift Lint

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'app/**'
      - '.github/workflows/swift-lint.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'app/**'
      - '.github/workflows/swift-lint.yml'

jobs:
  SwiftLint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: GitHub Action for SwiftLint
        uses: norio-nomura/action-swiftlint@3.2.1
        with:
          working-directory: app
